name: Build OpenWrt for Tinker Board S

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Pilih versi OpenWrt"
        required: true
        type: choice
        options:
          - "22.03.0"
          - "23.05.0"
          - "23.05.1"
          - "23.05.2"
          - "23.05.3"
          - "23.05.4"
          - "23.05.5"
          - "23.05.6"
          - "23.05.7"
          - "24.10.1"
          - "24.10.2"

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build OpenWrt ${{ github.event.inputs.version }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk           gettext git libncurses-dev libssl-dev python3 unzip zlib1g-dev           subversion libelf-dev ccache wget

    - name: Clone OpenWrt source ${{ github.event.inputs.version }}
      run: |
        VERSION=${{ github.event.inputs.version }}

        if [[ "$VERSION" == 22.03.* ]]; then
          BRANCH="openwrt-22.03"
        elif [[ "$VERSION" == 23.05.* ]]; then
          BRANCH="openwrt-23.05"
        elif [[ "$VERSION" == 24.* ]]; then
          BRANCH="master"
        else
          echo "Versi tidak dikenali: $VERSION"
          exit 1
        fi

        git clone --depth=1 -b $BRANCH https://git.openwrt.org/openwrt/openwrt.git
        cd openwrt
        git fetch --tags
        git checkout v$VERSION

    - name: Update & install feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Tambahkan DTS Tinker Board
      run: |
        mkdir -p openwrt/target/linux/armvirt/files/arch/arm/boot/dts/
        wget https://raw.githubusercontent.com/torvalds/linux/master/arch/arm/boot/dts/rk3288-tinker.dts -O openwrt/target/linux/armvirt/files/arch/arm/boot/dts/rk3288-tinker.dts
        wget https://raw.githubusercontent.com/torvalds/linux/master/arch/arm/boot/dts/rk3288.dtsi -O openwrt/target/linux/armvirt/files/arch/arm/boot/dts/rk3288.dtsi

    - name: Copy configuration files
      run: |
        cp configs/config.common openwrt/.config
        cp configs/extlinux.conf openwrt/output-sdboot/extlinux.conf
        cp configs/mkimage.sh openwrt/output-sdboot/mkimage.sh
        chmod +x openwrt/output-sdboot/mkimage.sh

    
- name: Build U-Boot
  run: |
    git clone --depth=1 https://github.com/TinkerBoard-Linux/rockchip-linux-u-boot.git uboot
    cd uboot
    export CROSS_COMPILE=arm-linux-gnueabi-
    make tinker_board_defconfig
    make -j$(nproc)
    cp u-boot.bin ../output-sdboot/u-boot.bin
    cp u-boot-spl-dtb.bin ../output-sdboot/u-boot-spl-dtb.bin

- name: Build OpenWrt
      run: |
        cd openwrt
        make defconfig
        make download -j$(nproc)
        make -j$(nproc) || make -j1 V=s

    - name: Prepare SD card files
      run: |
        cd openwrt/bin/targets/armvirt/32/
        mkdir -p ../../../output-sdboot
        cp zImage rk3288-tinker.dtb root.ext4.gz ../../../output-sdboot/
        cd ../../../output-sdboot
        gunzip root.ext4.gz
        mv root.ext4 rootfs.ext4
        tar -czf rootfs.tar.gz rootfs.ext4

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-tinkerboard-${{ github.event.inputs.version }}
        path: |
          openwrt/bin/targets/armvirt/32/
          openwrt/output-sdboot/
